### ISSUE TITLE
Production looks different from local dev.

### ISSUE THREAD

**Issue by Leemoonsoo** [ZEPL/zepl-documentation#20]
in Local dev env, it looks like
![image](https://user-images.githubusercontent.com/1540981/31710720-b3fce748-b3aa-11e7-96d4-827d455eeed0.png)

How ever in deployed production, looks like
![image](https://user-images.githubusercontent.com/1540981/31710662-8b9f09b6-b3aa-11e7-8add-aae11725f5d4.png)

**Comment by AhyoungRyu** [comment]
Hmm it's weird. This is what i see in prod now. 

<img width="1674" alt="screen shot 2017-10-18 at 6 28 43 pm" src="https://user-images.githubusercontent.com/10060731/31711140-3145cdfa-b432-11e7-8def-335de2c90237.png">

**Comment by Leemoonsoo** [comment]
I see style correctly in incognito mode.
but i see broken style in normal browsing mode in the same chrome browser, even after clear the cache.

Something wrong with my browser maybe

**Comment by Leemoonsoo** [comment]
Ah i restarted browser process and cleared that cache again. and it came back to normal!
I'm closing this issue.
